// ============================================
// Post page dynamic features (injected on every post):
//   1. Bilingual segmented toggle (mobile)
//   2. Share buttons (desktop + mobile)
//   3. Previous / next post navigation
// Each feature no-ops gracefully if the article doesn't match.
// POSTS_NAV below is regenerated by scripts/build.js on every build
// (ordered newest-first) — do not hand-edit between the markers.
// ============================================

/* BUILD:NAV_START */
var POSTS_NAV = [
  { slug: "why-overthink-on-an-empty-stomach", title: "做乜諗嘢唔食飯？｜Why Overthink on an Empty Stomach?", url: "/posts/why-overthink-on-an-empty-stomach" },
  { slug: "all-quiet-at-hastings", title: "喜士定無戰事｜All Quiet at Hastings", url: "/posts/all-quiet-at-hastings" },
  { slug: "candleblossoms", title: "蠟燭花｜Candle Blossoms", url: "/posts/candleblossoms" },
  { slug: "theballadoftheurgentbowels", title: "鳩佬極急便｜The Ballad of the Urgent Bowels", url: "/posts/theballadoftheurgentbowels" },
  { slug: "footbridge-paradox", title: "橋上悖論｜Paradox over the Footbridge", url: "/posts/footbridge-paradox" },
  { slug: "sisyphus", title: "推石頭之人｜He Who Pushes the Stone", url: "/posts/sisyphus" },
  { slug: "the-cat-teachers", title: "貓老師｜The Cat Teachers", url: "/posts/the-cat-teachers" },
  { slug: "bao-faan", title: "飽飯｜A Profound Satiety", url: "/posts/bao-faan" },
  { slug: "lands-end", title: "地之盡頭大風吹", url: "/posts/lands-end" }
];
/* BUILD:NAV_END */


// ============================================
// 1. Bilingual segmented toggle (mobile only)
//   - zh    : Chinese only (default)
//   - both  : Chinese + English stacked
//   - en    : English only
// CSS handles visibility; JS just toggles the class on .article-body.
// ============================================

(function () {
  const body = document.querySelector('.article-body');
  if (!body) return;

  const enParagraphs = body.querySelectorAll('.pair .en');
  if (enParagraphs.length === 0) return;  // pure-Chinese article: do nothing

  // Mark the English mirror text so screen readers switch voice and the
  // lang signal stays correct (the page itself is lang="zh-HK").
  enParagraphs.forEach(el => { if (!el.lang) el.lang = 'en'; });

  // build the segmented control
  const group = document.createElement('div');
  group.className = 'lang-toggle-group has-en';
  group.setAttribute('role', 'group');
  group.setAttribute('aria-label', '顯示語言/language display');

  const modes = [
    { key: 'zh',   label: '中' },
    { key: 'both', label: '中 + EN' },
    { key: 'en',   label: 'EN' }
  ];

  const buttons = modes.map(m => {
    const btn = document.createElement('button');
    btn.type = 'button';
    btn.className = 'lang-toggle';
    btn.dataset.mode = m.key;
    btn.textContent = m.label;
    if (m.key === 'zh') btn.classList.add('is-active');
    return btn;
  });

  buttons.forEach(b => group.appendChild(b));

  // insert before the article body
  body.parentNode.insertBefore(group, body);

  function setMode(mode) {
    body.classList.remove('mode-both', 'mode-en');
    if (mode === 'both') body.classList.add('mode-both');
    if (mode === 'en')   body.classList.add('mode-en');

    buttons.forEach(b => {
      b.classList.toggle('is-active', b.dataset.mode === mode);
    });
  }

  group.addEventListener('click', (e) => {
    const btn = e.target.closest('button[data-mode]');
    if (!btn) return;
    setMode(btn.dataset.mode);
  });
})();


// ============================================
// 2. Share buttons (all posts, desktop + mobile)
// Inject 5 text-only share links: threads / facebook /
// x / linkedin / copy link. Appended after .article-tags
// inside <article class="article">. Pure DOM injection
// so it applies to every post that loads post.js — old
// and new alike, with no per-post markup needed.
// ============================================

(function () {
  const article = document.querySelector('article.article');
  if (!article) return;

  // Avoid double-injection on hot reload / repeat scripts
  if (article.querySelector('.article-share')) return;

  const url = window.location.href;
  const titleEl = document.querySelector('.article-title');
  // .article-title may contain a <br><span> for bilingual subtitle.
  // Clone the element so we can mutate without affecting the page,
  // then replace <br> with " — " (em-dash) so the share text reads cleanly:
  // e.g. "飽飯 — A Profound Satiety" instead of "飽飯A Profound Satiety".
  let title;
  if (titleEl) {
    const clone = titleEl.cloneNode(true);
    clone.querySelectorAll('br').forEach(br => {
      br.replaceWith(document.createTextNode(' — '));
    });
    title = clone.textContent.replace(/\s+/g, ' ').trim();
  } else {
    title = document.title;
  }

  const encUrl = encodeURIComponent(url);
  const encTitle = encodeURIComponent(title);
  const encShareText = encodeURIComponent(`${title} — ${url}`);

  // Share target definitions. `href` = static link, `action` = JS handler.
  const targets = [
    {
      label: 'threads',
      href: `https://www.threads.net/intent/post?text=${encShareText}`
    },
    {
      label: 'facebook',
      href: `https://www.facebook.com/sharer/sharer.php?u=${encUrl}`
    },
    {
      label: 'x',
      href: `https://twitter.com/intent/tweet?url=${encUrl}&text=${encTitle}`
    },
    {
      label: 'linkedin',
      href: `https://www.linkedin.com/sharing/share-offsite/?url=${encUrl}`
    },
    {
      label: '複製連結/copy link',
      labelDone: '已複製/copied',
      labelFail: '複製失敗/copy failed',
      action: 'copy'
    }
  ];

  const wrap = document.createElement('div');
  wrap.className = 'article-share';
  wrap.setAttribute('role', 'group');
  wrap.setAttribute('aria-label', '分享呢篇/share this post');

  // Optional small label, matches the visual quietness of footer
  const lead = document.createElement('span');
  lead.className = 'article-share-lead';
  lead.textContent = '分享到/share to';
  wrap.appendChild(lead);

  targets.forEach(t => {
    const el = document.createElement(t.action ? 'button' : 'a');
    el.className = 'share-btn';
    el.textContent = t.label;

    if (t.action === 'copy') {
      el.type = 'button';
      el.addEventListener('click', async () => {
        const original = el.textContent;
        try {
          await navigator.clipboard.writeText(url);
          el.textContent = t.labelDone;
        } catch {
          // Fallback for browsers without clipboard API
          const ta = document.createElement('textarea');
          ta.value = url;
          ta.style.position = 'fixed';
          ta.style.opacity = '0';
          document.body.appendChild(ta);
          ta.select();
          try { document.execCommand('copy'); el.textContent = t.labelDone; }
          catch { el.textContent = t.labelFail; }
          document.body.removeChild(ta);
        }
        setTimeout(() => { el.textContent = original; }, 2000);
      });
    } else {
      el.href = t.href;
      el.target = '_blank';
      el.rel = 'noopener noreferrer';
    }

    wrap.appendChild(el);
  });

  // Insert after .article-tags if it exists, otherwise at end of article
  const tags = article.querySelector('.article-tags');
  if (tags && tags.parentNode === article) {
    tags.insertAdjacentElement('afterend', wrap);
  } else {
    article.appendChild(wrap);
  }
})();


// ============================================
// 3. Previous / next post navigation (all posts)
// Reads the build-generated POSTS_NAV (newest-first) at the top of this
// file, finds the current post by slug, and links its chronological
// neighbours: older on the left, newer on the right. No per-post markup —
// applies to every post that loads post.js, old and new alike.
// ============================================

(function () {
  const article = document.querySelector('article.article');
  if (!article) return;
  if (!Array.isArray(POSTS_NAV) || POSTS_NAV.length === 0) return;
  if (article.querySelector('.post-nav')) return;  // avoid double-injection

  // Current slug from the path: /posts/<slug> or /posts/<slug>.html
  const cleanPath = location.pathname.replace(/\.html$/, '').replace(/\/+$/, '');
  const slug = cleanPath.split('/').pop();

  const i = POSTS_NAV.findIndex(p => p.slug === slug);
  if (i === -1) return;  // template / unknown page

  const older = POSTS_NAV[i + 1] || null;  // array is newest-first
  const newer = POSTS_NAV[i - 1] || null;
  if (!older && !newer) return;

  const nav = document.createElement('nav');
  nav.className = 'post-nav';
  nav.setAttribute('aria-label', '更多文章/more posts');

  function makeLink(post, cls, label) {
    const a = document.createElement('a');
    a.className = cls;
    a.href = post.url;
    const l = document.createElement('span');
    l.className = 'nav-label';
    l.textContent = label;
    const t = document.createElement('span');
    t.className = 'nav-title';
    t.textContent = post.title;
    a.appendChild(l);
    a.appendChild(t);
    return a;
  }

  if (older) nav.appendChild(makeLink(older, 'nav-older', '← 較舊/older'));
  if (newer) nav.appendChild(makeLink(newer, 'nav-newer', '較新/newer →'));

  // Place it after the share buttons (which sit after .article-tags)
  const share = article.querySelector('.article-share');
  const tags = article.querySelector('.article-tags');
  if (share) share.insertAdjacentElement('afterend', nav);
  else if (tags) tags.insertAdjacentElement('afterend', nav);
  else article.appendChild(nav);
})();
